config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'patients/new'

  get 'patients/create'

  get 'patients/update'

  get 'patients/edit'

  get 'patients/destroy'

  get 'patients/show'

  get 'patients/index'

  get 'welcome/index'

  root 'welcome#index'

  resources :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base
    validates :name, presence: true,
                     length:  { minimum: 5 }
    validates :age,  presence: true
    validates :provider, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  include Gravtastic
  gravtastic
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # Add title variable
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    
    if @patient.save
      redirect_to @patient
    else
      render 'new'
    end
  end

  def update
    @patient = Patient.find(params[:id])
    
    if @patient.update(patient_params)
      redirect_to @patient
    else
      render 'edit'
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    
    redirect_to patients_path
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def index
    @patients = Patient.all
  end
  
  private
    def patient_params
      params.require(:patient).permit(:name, :age, :provider)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @html_sub_title = "Welcome | Ivory"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @html_sub_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= evil_icons_sprite %>

  <div class="uk-grid">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </div>

    <header class="uk-width-1-1 border-bottom">
        <h1 style="margin-bottom: 20px;" class="uk-align-left margin-left-large margin-top-large margin-bottom-large">
          <%= link_to 'Ivory', '/', class: 'uk-text-bold' %>
        </h1>

        <ul class="uk-list uk-float-right margin-right-large">
          <% if user_signed_in? %>
            <a href='#menu-modal' data-uk-modal>
              <%= image_tag current_user.gravatar_url, style: 'height:50px;' %>
            </a>
          <% else %>
            <li><a href="#menu-modal" data-uk-modal><%= evil_icon 'ei-navicon', size: :m %></a></li>
          <% end %>
        </ul>
    </header>

    <!-- Modals -->

    <div id="menu-modal" class="uk-modal">
      <div class="uk-modal-dialog uk-modal-dialog-large uk-height-viewport uk-vertical-align">
        <div class="uk-width-large-1-6 uk-width-medium-2-10 uk-width-small-1-10 uk-vertical-align-middle"></div>
        <div class="uk-width-large-2-6 uk-width-medium-2-6  uk-width-small-4-10 uk-vertical-align-middle border-right menu-panel" style="padding-right: 100px;">

          <% if user_signed_in? %>
            <div class="uk-display-block">
              <h2 style="margin: 0px;" class="uk-text-right">Welcome</h2>
              <h6 style="margin: 0px;" class="uk-text-right uk-text-muted"><%= current_user.email %></h6>
            </div>
            <ul class="uk-list uk-list-space uk-text-large uk-text-right margin-top-large">
              <li>My profile</li>
              <li>Recent activities</li>
              <li>Upcoming tasks</li>
              <li>Provider</li>
              <li>Integrations</li>
            </ul>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'uk-button uk-button-default uk-width-1-1 uk-button-large margin-top' %>
          <% else %>
            <h2>Members</h2>
            <%= form_for(:user, class: 'uk-form uk-form-stacked', url: '/users/sign_in') do |f| %>
              <div class="uk-form-row">
                <div class="uk-form-controls">
                  <%= f.email_field :email, autofocus: true, placeholder: 'Your email', style: 'height: 50px; padding-left: 15px; padding-top: 15px; padding-bottom: 15px;', class: 'uk-width-1-1 uk-form-large' %>
                  <%= f.password_field :password, autocomplete: "off", placeholder: 'Your password', style: 'height: 50px; padding-left: 15px; padding-top: 15px; padding-bottom: 15px;', class: 'uk-width-1-1 uk-form-large margin-top' %>
                  <%= f.submit "Sign in", class: 'uk-button uk-button-primary uk-button-large uk-width-1-1 margin-top-large' %>
                </div>
              <h5 class="uk-float-right button-sub-text"><a href="/users/password/new" class="uk-button uk-button-default uk-button-small">Forgot your password?</a></h5>
            <% end %>

            <br><br>
            <h2>Enrolled to Ivory?</h2>
            <a class="button uk-button uk-button-default uk-button-large uk-width-1-1" href="/users/sign_up">Create account</a>
            <h5 class="button-sub-text text-alt">Physician not participating? <a href="#">Ask why</a></h5>
          </div>
          <% end %>
        </div>

        <div class="uk-width-large-2-6 uk-width-medium-2-6 uk-width-small-4-10 uk-vertical-align-middle menu-panel" style="padding-left: 100px;">
          <ul class="uk-list uk-list-space uk-text-large">
            <li>Search doctors, benifits, and more</li>
            <li>Frequently Asked Questions</li>
            <li>Provider Portal</li>
            <li>Ivory blog</li>
            <li>Careers</li>
            <li>Press</li>
          </ul>

          <ul class="uk-list text-alt margin-top-large">
            <li>Privacy Policy</li>
            <li>Our Terms of Service</li>
          </ul>
        </div>
        <div class="uk-width-large-1-6 uk-width-medium-2-10 uk-width-small-1-10 uk-vertical-align-middle"></div>
      </div>
    </div>

    <%= yield %>

  </div>

</body>
</html>

app/views/patients/create.html.erb
<h1>Patients#create</h1>
<p>Find me in app/views/patients/create.html.erb</p>

app/views/patients/destroy.html.erb
<h1>Patients#destroy</h1>
<p>Find me in app/views/patients/destroy.html.erb</p>

app/views/patients/edit.html.erb
<h1>Editing Patient/h1>
 
<%= form_for :patient, url: patient_path(@patient), method: :patch do |f| %>
 
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient.errors.count, "error") %> prohibited
        this patient from being saved:
      </h2>
      <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :age %><br>
    <%= f.text_field:age %>
  </p>
  
  <p>
      <%= f.label :provider %><br>
      <%= f.select :provider, [['Please choose provider', nil], 'McGregger, She', 'Reichardt, Matthew'] %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Patients</h1>
<p>Patients currently enrolled</p>

<%= link_to 'Add Patient', new_patient_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Provider</th>
    <th colspan="3"></th>
  </tr>
 
  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.name %></td>
      <td><%= patient.age %></td>
      <td><%= patient.provider %></td>
      <td><%= link_to 'Show', patient_path(patient) %></td>
      <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
      <td><%= link_to 'Destroy', patient_path(patient),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  
</table>

app/views/patients/new.html.erb
<h1>Add a patient</h1>

<%= form_for :patient, url: patients_path do |f| %>

  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@patient.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </p>
  
  <p>
    <%= f.label :provider %><br>
    <%= f.select :provider, [['Please choose provider', nil], 'McGregger, She', 'Reichardt, Matthew'] %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/patients/show.html.erb
<h1>Patient added</h1>
<p>Confirmation of patient added</p>

<p>
    <strong>Name:</strong>
    <%= @patient.name %>
</p>
<p>
    <strong>Age:</strong>
    <%= @patient.age %>
</p>
<p>
    <strong>Provider:</strong>
    <%= @patient.provider %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/patients/update.html.erb
<h1>Patients#update</h1>
<p>Find me in app/views/patients/update.html.erb</p>

app/views/welcome/index.html.erb
<%= evil_icons_sprite %>

<section style="margin-top: 70px;" class="uk-vertical-align uk-width-1-1 hero border-bottom bg-alt">

  <% if !user_signed_in? %>
    <div class="uk-vertical-align-middle uk-width-1-4"></div>
    <div class="uk-vertical-align-middle uk-width-1-2 uk-container-center margin-bottom-large">
      <h2 class="uk-text-center">How much could the world benifit from better preventative health-care?</h2>
    </div>
    <div class="uk-vertical-align-middle uk-width-1-4"></div>

    <div class="uk-width-large-1-4 uk-width-medium-1-2 uk-small-1-2 uk-vertical-align-middle uk-text-center">
      <%= evil_icon 'ei-clock', size: :l %>
      <h2>It's time</h2>
      <p class="call-to-actions">Easily keep track of what matters: your health. Get notified when
        it's time for that next check-up</p>
    </div>
    <div class="uk-width-large-1-4 uk-width-medium-1-2 uk-small-1-2 uk-vertical-align-middle uk-text-center">
      <%= evil_icon 'ei-exclamation', size: :l %>
      <h2>Uh-oh</h2>
      <p class="call-to-actions">Life make you miss that checkin? We've got your back with notifications
        to take your vitals, and more.</p>
    </div>
    <div class="uk-width-large-1-4 uk-width-medium-1-2 uk-small-1-2 uk-vertical-align-middle uk-text-center">
      <%= evil_icon 'ei-user', size: :l %>
      <h2>Connect...</h2>
      <p class="call-to-actions">...with your physicians in an easy-to-use, fun way. Get alerts when your
      physician has sent you a update.</p>
    </div>
    <div class="uk-width-large-1-4 uk-width-medium-1-2 uk-small-1-2 uk-vertical-align-middle uk-text-center">
      <%= evil_icon 'ei-trophy', size: :l %>
      <h2>Points matter</h2>
      <p class="call-to-actions">Ever had a incentive to be healthy? Treat yourself right and accrue
      points towards cool gifts and more.</p>
    </div>

  <% else %>

    <div class="uk-width-large-1-4 uk-width-medium-1-2 uk-small-1-2 uk-vertical-align-middle uk-text-center">
      <%= image_tag current_user.gravatar_url %>
      <h2>Uh-oh</h2>
      <p class="call-to-actions">Life make you miss that checkin? We've got your back with notifications
        to take your vitals, and more.</p>
    </div>

  <% end %>

</section>